### ISSUE TITLE
OSC - Phone number of Sign-up page should have '+' prefix

### ISSUE THREAD

**Issue by sareenEminds** [beckn/OSM-app#158]
## Description

Phone number in the sign up page should have a '+' and the length validation should be removed

## Goals

- [x] Phone number should have '+' as prefix
- [x] Validation of the length of the phone number should be removed

## Expected Outcome

A user should be able to sign-up with a phone number having a prefix '+' and any length.

## Acceptance Criteria

- [x] Phone number should have a '+' as prefix
- [x] Phone number can be of any length

## Implementation Details

The phone number should have uneditable '+' as a prefix. The phone number length validation should be removed.

---

### Product Name

OSC

### Domain

Retail

### Tech Skills Needed:

NextJS

### Complexity

Low

### Category

Enhancement

**Comment by ujjwal502** [comment]
since @skrushna1704 is on leave, I am updating here on his behalf

Here is the PR that includes the fix of the above
[https://github.com/beckn/OSM-app/pull/157](url)

@sareenEminds @meenakshi2468 @viraj89 Please review

**Comment by ujjwalEminds** [comment]
done, and raised PR, also PR merged on Dev
Here is the PR that includes the fix of the above
[https://github.com/beckn/OSM-app/pull/157](https://github.com/beckn/OSM-app/issues/url)
@sareenEminds @ujjwal502

**Comment by skrushna1704** [comment]
done, and raised PR, also PR merged on Dev
Here is the PR that includes the fix of the above
[https://github.com/beckn/OSM-app/pull/157](https://github.com/beckn/OSM-app/issues/url)
@sareenEminds @ujjwal502

**Comment by meenakshi2468** [comment]
Please mark as 'Done', if this is completed.

CC: @sareenEminds @viraj89
