### ISSUE TITLE
OSC - Description and Price are overlapped

### ISSUE THREAD

**Issue by sareenEminds** [beckn/OSM-app#160]
## Description

The items displayed on the search results page the description of the item and the price are overlapped.

## Goals

- [ ] The price and description of the item should be separated without an overlap.

## Expected Outcome

The price and description of an item should be readable

## Acceptance Criteria

- [ ] The price and description of an item should not overlap

## Implementation Details

There should be space added between the price and description of an item on a desktop screen.

---

### Product Name

OSC

### Domain

Retail

### Tech Skills Needed:

NextJS

### Complexity

Low

### Category

Enhancement

**Comment by skrushna1704** [comment]
done, and raised PR, also PR merged on Dev
Here is the PR that includes the fix of the above
[https://github.com/beckn/OSM-app/pull/157](https://github.com/beckn/OSM-app/issues/url)
@sareenEminds @ujjwal502

**Comment by skrushna1704** [comment]
done, and raised PR, also PR merged on Dev
Here is the PR that includes the fix of the above
[https://github.com/beckn/OSM-app/pull/157](https://github.com/beckn/OSM-app/issues/url)
@sareenEminds @ujjwal502
