### ISSUE TITLE
OSC - The workflow should work without location access

### ISSUE THREAD

**Issue by sareenEminds** [beckn/OSM-app#161]
## Description

The entire retail flow should still work without the location.

## Goals

- [ ] The retail flow should proceed even when the location access is not allowed

## Expected Outcome

The retail flow should be possible when location access is disabled

## Acceptance Criteria

- [ ] The location access should be denied and the retail flow should not be effected

## Implementation Details

The retail order flow should not be effected when location access is denied. The search should be sent without the location information

---

### Product Name

OSC

### Domain

Retail

### Tech Skills Needed:

NextJS

### Complexity

Medium

### Category

Enhancement

**Comment by skrushna1704** [comment]
@ujjwal502 @sareenEminds 
please check and merge
https://github.com/beckn/OSM-app/pull/175
