### ISSUE TITLE
OSC - The search fails when re-tried after a success

### ISSUE THREAD

**Issue by sareenEminds** [beckn/OSM-app#162]
## Description

The search function fails on the second try.

## Goals

- [ ] The search should be able to succeed after 1st search

## Expected Outcome

The user should be able to redo the search any number of time after the initial search

## Acceptance Criteria

- [ ] The search should be able to be redone after the first try

## Implementation Details

After the first search the next searches should not be sending the provider id in the search request

---

### Product Name

OSC

### Domain

Retail

### Tech Skills Needed:

NextJS

### Complexity

Low

### Category

Bug

**Comment by meenakshi2468** [comment]
Please mark as 'Done', if this is completed.

CC: @sareenEminds @viraj89

**Comment by skrushna1704** [comment]
@ujjwal502 @sareenEminds 
please check and merge
https://github.com/beckn/OSM-app/pull/175
