### ISSUE TITLE
OSC - EURO symbol should be as prefix on the price

### ISSUE THREAD

**Issue by sareenEminds** [beckn/OSM-app#163]
## Description

The price when the currency is EURO the currency symbol should be as prefix rather than postfix.

## Goals

- [ ] The euro currency symbol should be a prefix

## Expected Outcome

The price should have the euro symbol as prefix

## Acceptance Criteria

- [ ] When currency is EURO the price should have euro symbol as prefix

## Implementation Details

The utility used to format the currency should be changed to have the above mentioned

---

### Product Name

OSC

### Domain

Retail

### Tech Skills Needed:

NextJS

### Complexity

Low

### Category

Enhancement

**Comment by skrushna1704** [comment]
please check and merge
https://github.com/beckn/OSM-app/pull/166
@sareenEminds @ujjwal502

**Comment by meenakshi2468** [comment]
Please mark as 'Done', if this is completed.

CC: @sareenEminds @viraj89
