### ISSUE TITLE
OSC - Remove the hover functionality on the cart button

### ISSUE THREAD

**Issue by sareenEminds** [beckn/OSM-app#165]
## Description

The hover functionality should be removed when cursor is on the cart button. This is on the desktop resolution that there is a bad experience due to this.

## Goals

- [ ] Remove the hover functionality on the cart button

## Expected Outcome

The cart information should not be shown on hover on the cart button

## Acceptance Criteria

- [ ] The hover functionality should be removed on the cart button

## Implementation Details

Remove the code related to the hover functionality on the cart button

---

### Product Name

OSC

### Domain

Retail

### Tech Skills Needed:

NextJS

### Complexity

Low

### Category

Enhancement

**Comment by skrushna1704** [comment]
please check and merge
https://github.com/beckn/OSM-app/pull/166
@ujjwal502 @sareenEminds

**Comment by meenakshi2468** [comment]
Please mark as 'Done', if this is completed.

CC: @sareenEminds @viraj89
