### ISSUE TITLE
OSC - Create a payment failed page 

### ISSUE THREAD

**Issue by sareenEminds** [beckn/OSM-app#168]
## Description

A new payment failed page should be create when a payment on stripe has a failure

## Goals

- [ ] A new payment informing of a payment failure

## Expected Outcome

A new page should be included which indicate the failure of payment

## Acceptance Criteria

- [ ] A payment failure page should be designed for showcase a failure during the checkout process

---

### Product Name

OSC

### Domain

Retail

### Tech Skills Needed:

UI/UX

### Complexity

Low

### Category

Enhancement

**Comment by UmangAtal97** [comment]
Hey @meenakshi2468 Yes

**Comment by UmangAtal97** [comment]
Design for the requested screen is complete and reviewed by @sareenEminds 

Figma Link:
[https://www.figma.com/file/LIoFOsrvQayGcn17btYbHE/Open-Amsterdam?type=design&node-id=14-5992&mode=design](url)

CC: @viraj89 @sareenEminds @meenakshi2468

**Comment by meenakshi2468** [comment]
@sareenEminds : Do we need a new issue ticket for 'developing a UI screen' for this?

@viraj89 : Please capture these information in Confluence - I have added this to Confluence page: https://fide-official.atlassian.net/wiki/spaces/TPP/pages/204865554/Links+for+Pilot+Launch
