### ISSUE TITLE
OSC - Create payment failure page

### ISSUE THREAD

**Issue by sareenEminds** [beckn/OSM-app#173]
## Description

Create a payment failure page which will be used in the payment flow 

## Goals

- [ ] Create a payment failure page

## Expected Outcome

When a payment failure during the checkout process this page should be shown

## Acceptance Criteria

- [ ] When a payment fails the failure page should be displayed

## Implementation Details

- When the payment process fails during the checkout flow the payment page should be displayed
![Screenshot 2024-03-15 at 10 50 47 AM](https://github.com/beckn/OSM-app/assets/149787376/5ed2c796-01ec-4e58-a590-63a5268155be)

---

### Product Name

OSC

### Domain

Retail

### Tech Skills Needed:

NextJS

### Complexity

Low

### Category

Enhancement

**Comment by skrushna1704** [comment]
@ujjwal502 @sareenEminds 
please check and merge
https://github.com/beckn/OSM-app/pull/175
